import categoriesData from "./categories.json";
import getInTouchData from "./get-in-touch.json";
import officesData from "./offices.json";
import partnersData from "./partners.json";
import projectsData from "./projects.json";
import thoughtsData from "./thoughts.json";
import studiosData from "./studios.json";
import homeData from "./pages/home/home.json";
import servicesData from "./pages/services/services.json";
import workData from "./pages/work/work.json";
import thoughtsPageData from "./pages/thoughts/thoughts.json";
import policiesData from "./policies.json";

export const categories = categoriesData;
export const getInTouch = getInTouchData;
export const offices = officesData;
export const partners = partnersData;
export const projects = projectsData;
export const studios = studiosData;
export const home = homeData;
export const services = servicesData;
export const work = workData;
export const thoughtsPage = thoughtsPageData;
export const thoughts = thoughtsData;
export const policies = policiesData;
